spring:
  flyway:
    locations: classpath:/db/migration
    check-location: false
    enabled: false
  h2:
    console:
      enabled: true
  datasource:
    url: 'jdbc:h2:~/testdb;DB_CLOSE_ON_EXIT=FALSE'
    driverClassName: 'org.h2.Driver'
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: 'org.hibernate.dialect.H2Dialect'
    hibernate:
      ddl-auto: none
    properties:
      hibernate.enable_lazy_load_no_trans: true

  main:
    allow-bean-definition-overriding: true

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: '#'
    password: '#'
    properties.mail.smtp:
      auth: true
      starttls.enable: true

app:
  url: "http://localhost:8080"
  clientId: "base-app-dev"
  clientSecret: "E7hNRnx37kmQqYx7Xc7dCt68BdP7gXPJ"